<div id="locator_filter-store" class="block" style="display: flex;">
    <div class="column_left" style="width: 100%">
		<div class="center store_wrapper"> 
			<div class="store_list"><?= $block->getChildHtml('store_list_view') ?></div>
		</div>
    </div>	
</div>
<script language="javascript" type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=<?php echo $block->getApiKey() ?>&libraries=places"></script>
<script>
    var baloonTemplate = <?php echo $block->getBaloonTemplate() ?>;
</script>
<script>
    require([
        'jquery',
        'Rokanthemes_StoreLocator/js/viewmap',
        'Rokanthemes_StoreLocator/js/cluster',
        'domReady!'
    ], function ($) {
        $('#bst-map-view').bstLocatorView({
            jsonLocations: <?php echo $this->getJsonLocations() ?>,
			imageShop: "<?php echo $block->getViewFileUrl('Rokanthemes_StoreLocator::images/shop.jpg'); ?>",
            imageLocations: "<?php echo $block->getViewFileUrl('Rokanthemes_StoreLocator::images/'); ?>"
        })
    });
</script>

