<?php
/**
 * Copyright © 2015 RokanThemes.com. All rights reserved.

 * @author RokanThemes Team <contact@rokanthemes.com>
 */
?>
<?php
/**
 * Blog post view template
 *
 * @var $block \Rokanthemes\Blog\Block\Post\View
 */
?>
<?php
    $_post = $this->getPost();
    $_postUrl = $_post->getPostUrl();
    $_postNameStripped = $block->stripTags($_post->getTitle(), null, true);
	$_postName = $block->escapeHtml($_post->getTitle(), null, true);
?>
<div class="post-view col-sm-9">
    <div class="post-holder post-holder-<?php echo $_post->getId() ?>">
        <div class="post-content">
            <div class="post-description">
                <?php echo $block->getContent() ?>
                <div class="clear"></div>
            </div>
        </div>
		 <div class="post-header clearfix">
            <div class="addthis_toolbox addthis_default_style" addthis:url="<?php echo $_postUrl ?>">
                <a class="addthis_button_facebook"></a>
                <a class="addthis_button_twitter"></a>
                <a class="addthis_button_email"></a>
                <a class="addthis_button_compact"></a>
            </div> 
        </div>
        <div class="post-bottom">
            <?php echo $this->getChildHtml('blog.post.bottom') ?>
        </div>
    </div>
</div>