<?php
$showWishlist = true;
switch ($type = $block->getType()) {

    case 'related-rule':
        if ($exist = $block->hasItems()) {
            $type = 'related';
            $class = $type;

            $image = 'related_products_list';
            $title = __('Related Products');
            $items = $block->getAllItems();
            $limit = $block->getPositionLimit();
            $shuffle = (int) $block->isShuffled();
            $canItemsAddToCart = $block->canItemsAddToCart();
			
            $showAddTo = true;
            $showCart = false;
            $templateType = null;
            $description = false;
        }
    break;

    case 'related':
        /** @var \Magento\Catalog\Block\Product\ProductList\Related $block */
        if ($exist = $block->getItems()->getSize()) {
            $type = 'related';
            $class = $type;

            $image = 'related_products_list';
            $title = __('Related Products');
            $items = $block->getItems();
            $limit = 0;
            $shuffle = 0;
            $canItemsAddToCart = $block->canItemsAddToCart();

            $showAddTo = true;
            $showCart = false;
            $templateType = null;
            $description = false;
        }
    break;

    case 'upsell-rule':
        if ($exist = $block->hasItems()) {
            $type = 'upsell';
            $class = $type;

            $image = 'upsell_products_list';
            $title = __('We found other products you might like!');
            $items = $block->getAllItems();
            $limit = $block->getPositionLimit();
            $shuffle = (int) $block->isShuffled();

            $showAddTo = false;
            $showCart = false;
            $templateType = null;
            $description = false;
            $canItemsAddToCart = false;
        }
    break;

    case 'upsell':
        /** @var \Magento\Catalog\Block\Product\ProductList\Upsell $block */
        if ($exist = count($block->getItemCollection()->getItems())) {
            $type = 'upsell';
            $class = $type;

            $image = 'upsell_products_list';
            $title = __('We found other products you might like!');
            $items = $block->getItemCollection()->getItems();
            $limit = $block->getItemLimit('upsell');
            $shuffle = 0;

            $showAddTo = false;
            $showCart = false;
            $templateType = null;
            $description = false;
            $canItemsAddToCart = false;
        }
    break;

    case 'crosssell-rule':
        /** @var \Magento\Catalog\Block\Product\ProductList\Crosssell $block */
        if ($exist = $block->hasItems()) {
            $type = 'crosssell';
            $class = $type;

            $image = 'cart_cross_sell_products';
            $title = __('More Choices:');
            $items = $block->getItemCollection();

            $showAddTo = true;
            $showCart = true;
            $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
            $description = false;
            $canItemsAddToCart = false;
        }
    break;

    case 'crosssell':
        /** @var \Magento\Catalog\Block\Product\ProductList\Crosssell $block */
        if ($exist = count($block->getItems())) {
            $type = 'crosssell';
            $class = $type;

            $image = 'cart_cross_sell_products';
            $title = __('More Choices:');
            $items = $block->getItems();

            $showAddTo = true;
            $showCart = true;
            $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
            $description = false;
            $canItemsAddToCart = false;
        }
    break;

    case 'new':
        if ($exist = $block->getProductCollection()) {
            $type = 'new';
            $mode = 'grid';
            $type = $type . ' ' . $mode;

            $class = 'widget' . ' ' . $type;

            $image = 'new_products_content_widget_grid';
            $title = __('New Products');
            $items = $exist;

            $showAddTo = true;
            $showCart = true;
            $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
            $description = ($mode == 'list') ? true : false;
            $canItemsAddToCart = false;
        }
    break;

    default:
        $exist = null;
}
?>

<?php if ($exist):?>
<?php if ($type == 'related' || $type == 'upsell'): ?>
<?php if ($type == 'related'): ?>
<section class="block <?php echo $class; ?>" data-mage-init='{"relatedProducts":{"relatedCheckbox":".related.checkbox"}}' data-limit="<?php echo $limit; ?>" data-shuffle="<?php echo $shuffle; ?>">
<?php else: ?>
<section class="block <?php echo $class; ?>" data-mage-init='{"upsellProducts":{}}' data-limit="<?php echo $limit; ?>" data-shuffle="<?php echo $shuffle; ?>">
<?php endif; ?>
<?php else: ?>
<section class="block <?php echo $class; ?>">
   <?php endif; ?>
	<div class="rokan-product-heading"> 
		<h2><?php echo $title; ?></h2>
		<?php if ($type == 'related' && $canItemsAddToCart) :?>
			<div class="block-actions">
				<?= $block->escapeHtml(__('Check items to add to the cart or')) ?>
				<button type="button" class="action select" data-role="select-all"><span><?= $block->escapeHtml(__('select all')) ?></span></button>
			</div>
		<?php endif; ?>		
	</div>
	<div class="block-content content owl-product" aria-labelledby="block-<?php echo $class?>-heading">
		<div class="row">
			<div id="relate_product_slider_<?php echo $type;?>" class="owl-carousel">
				<?php $iterator = 1; ?>
				<?php 
					$i = 0;
					$rows = 1;
				?>
				<?php foreach ($items as $_item): ?>
				<?php $available = ''; ?>
				<?php if (!$_item->isComposite() && $_item->isSaleable() && $type == 'related'): ?>
				<?php if (!$_item->getRequiredOptions()): ?>
				<?php $available = 'related-available'; ?>
				<?php endif; ?>
				<?php endif; ?>
			<?php
					$productImage = $block->getImage($_item, $image);
			?>	
				<?php if ($i++%$rows==0) { ?>
					<div class="product-item">
				<?php } ?>
					<div class="item-inner">
						<div class="product-photo">
							<a href="<?php /* @escapeNotVerified */ echo $_item->getProductUrl() ?>" class="product photo product-item-photo" tabindex="-1">
								<?php $productImageThumb = $block->getImage($_item, 'category_page_grid-1');?>
								<span class="image0 image-switch">
									<?php echo $productImage->toHtml(); ?>
								</span>
								<span class="image1 image-switch">
									<?php echo $productImageThumb->toHtml(); ?>
								</span>
							</a>							
							<ul class="add-to-links">
								<?php if( $showWishlist ): ?>
                                <?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow()): ?>
									<li>
										<a href="#"
										   class="action button towishlist"
										   title="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>"
										   aria-label="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>"
										   data-post='<?php /* @escapeNotVerified */ echo $block->getAddToWishlistParams($_item); ?>'
										   data-action="add-to-wishlist"
										   role="button">
											<i class="icon-heart"></i>
										</a>
									</li>
								<?php endif; ?>
								<?php endif; ?>				
								<?php
										$compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare'); 
									?>
									<li><a href="#"
										   class="action button tocompare"
										   title="<?php echo $block->escapeHtml(__('Add to Compare')); ?>"
										   aria-label="<?php echo $block->escapeHtml(__('Add to Compare')); ?>"
										   data-post='<?php /* @escapeNotVerified */ echo $compareHelper->getPostDataParams($_item); ?>'
										   role="button">
											<i class="icon-layers"></i>
										</a>
									</li>	
							</ul>
							<?php if ($canItemsAddToCart && !$_item->isComposite() && $_item->isSaleable() && $type == 'related') :?>
								<?php if (!$_item->getRequiredOptions()) :?>
									<div class="field choice related">
										<input type="checkbox" class="checkbox related" id="related-checkbox<?= $block->escapeHtmlAttr($_item->getId()) ?>" name="related_products[]" value="<?= $block->escapeHtmlAttr($_item->getId()) ?>" />
										<label class="label" for="related-checkbox<?= $block->escapeHtmlAttr($_item->getId()) ?>"><i class="icon-shopping-bag"></i></label>
									</div>
								<?php endif; ?>
							<?php endif; ?>								
							<div class="product-label">
								<?php if ( $_item->getFinalPrice() < $_item->getPrice() ): ?>
									<span class="onsale">
										<span class="sale-bg"></span>
										<span class="sale-text"><?php echo __('Sale') ?></span>
									</span>
								<?php endif; ?>
								<?php $todayDate = time(); 
									$timeStartNew = strtotime($_item->getData('news_from_date'));
									$timeEndNew = strtotime($_item->getData('news_to_date')); ?>
								<?php if ( $timeEndNew >= $todayDate && $timeStartNew <= $todayDate): ?>
									<span class="newlabel">
										<span><?php echo __('New') ?></span>
									</span>
								<?php endif; ?>
							</div>
						</div>
						<div class="product-info">
							<div class="product-infor-top">
								<div class="product-category">
									<?php 
									$objectManager = \Magento\Framework\App\ObjectManager::getInstance(); 
									$categories = $_item->getCategoryIds();
									foreach($categories as $key=>$category){
										$cat = $objectManager->create('Magento\Catalog\Model\Category')->load($category); 
									?> 
										<a href="<?php echo $cat->getUrl() ?>"><?php  echo $cat->getName(); ?></a>
										<?php if($key < 1){ echo ' , '; }?>
										<?php if($key == 1){ break; }?>
									<?php	} ?> 
								</div>	
								<?php echo $block->getReviewsSummaryHtml($_item, $templateType,true); ?>
							</div>									
							<strong class="product name">
								<a class="product-item-link" title="<?php echo $block->escapeHtml($_item->getName()) ?>" href="<?php echo $block->getProductUrl($_item) ?>">
								<?php echo $block->escapeHtml($_item->getName()) ?></a>
							</strong>
							<?php echo $block->getProductPrice($_item); ?>						
							<?php if ($showAddTo || $showCart) :?>
								<div class="product actions product-item-actions">
									<?php if ($showCart) :?>
										<div class="actions-primary">
											<?php if ($_item->isSaleable()) :?>
												<?php if ($_item->getTypeInstance()->hasRequiredOptions($_item)) :?>
													<button class="action tocart primary" data-mage-init='{"redirectUrl": {"url": "<?= $block->escapeUrl($block->getAddToCartUrl($_item)) ?>"}}' type="button" title="<?= $block->escapeHtmlAttr(__('Add to Cart')) ?>">
														<span><?= $block->escapeHtml(__('Add to Cart')) ?></span>
													</button>
												<?php else :?>
													<?php $postDataHelper = $this->helper(Magento\Framework\Data\Helper\PostHelper::class);
													$postData = $postDataHelper->getPostData($block->escapeUrl($block->getAddToCartUrl($_item)), ['product' => $_item->getEntityId()])
													?>
													<button class="action tocart primary"
															data-post='<?= /* @noEscape */ $postData ?>'
															type="button" title="<?= $block->escapeHtmlAttr(__('Add to Cart')) ?>">
														<span><?= $block->escapeHtml(__('Add to Cart')) ?></span>
													</button>
												<?php endif; ?>
											<?php else :?>
												<?php if ($_item->getIsSalable()) :?>
													<div class="stock available"><span><?= $block->escapeHtml(__('In stock')) ?></span></div>
												<?php else :?>
													<div class="stock unavailable"><span><?= $block->escapeHtml(__('Out of stock')) ?></span></div>
												<?php endif; ?>
											<?php endif; ?>
										</div>
									<?php endif; ?>
								</div>
							<?php endif; ?>

						</div>

					</div> 
				<?php if($i%$rows==0 || $i == count($items)) { ?> 
				</div> 
				<?php } ?>
				<?php endforeach ?>
			</div>
		</div>
    </div>

</section>
<?php endif;?>
<script type="text/javascript">
	require([
		'jquery',
		'mage/mage',
		'rokanthemes/owl'
	], function ($) {
		'use strict';

		jQuery("#relate_product_slider_<?php echo $type;?>").owlCarousel({
			lazyLoad: true,
			autoPlay : false,
			items : 5,
			itemsDesktop : [1199,4],
			itemsDesktopSmall : [980,3],
			itemsTablet: [768,2],
			itemsMobile : [479,1],
			slideSpeed : 500,
			paginationSpeed : 500,
			rewindSpeed : 500,
			navigation : true,
			stopOnHover : true,
			pagination :false,
			scrollPerPage:true,
		});
	});
</script>