<div id="back-top" class=""><?php /* @escapeNotVerified */ echo __('SCROLL UP'); ?><i class="fa fa-angle-double-right"></i></div>
<div class="footer-container layout3">
	<div class="footer-newsletter">
			<?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('footer_newsletter')->toHtml();?>
	</div>
	<div class="footer-bg">
		<div class="container">
			<div class="footer-static-container">
				<div class="footer_introduce">
					<div class="footer-introduce">
						<?php echo $this->getChildHtml("footer_introduce"); ?> 
					</div>
					<div class="menu-hozital"> 
						<?php echo $this->getChildHtml("footer_menu"); ?> 
					</div>
					<div class="copyright">
						<?php  echo $this->getLayout()->createBlock("Rokanthemes\Themeoption\Block\Customcss")->setTemplate("html/copyright.phtml")->toHtml() ?>
					</div>
				</div>
				<div class="footer-menu">
					<div class="footer-links"> 
						<?php echo $this->getChildHtml("footer_menu_middle"); ?> 
					</div>
				</div>
				<div class="footer-social-text">
					<div class="footer-links">
						<?php echo $this->getChildHtml("social_block"); ?> 
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
<script>
	window.onload = function () { 
		document.body.className += " preloaded";
	}
</script>

