<?php 
	use Magento\Framework\App\Action\Action;
	$category_load = $block->getCategory();
	if($category_load && strtotime($block->getConfig('end_date')) >= strtotime($block->getCurrentTime())){ 
		$image = 'new_products_content_widget_grid';
	$background = '';
	if($this->getConfig('background_image')){
		$folderName = \Rokanthemes\Themeoption\Model\Config\Superdealsbackground::UPLOAD_DIR;
		$path = $folderName . '/' . $this->getConfig('background_image');
		$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
		$storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
		$imageUrl = $storeManager->getStore()->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_MEDIA).$path;
		$background = "style='background-image: url(".$imageUrl.");'";
	}
?>
<div class="super-deal" <?php echo $background ?>> 
		<div class="super-deal-header-content">
			<div class="col-countdown">
				<div class="supper-deal-title">
					<p class="hotdeal"><span><?php echo __('hot <br/> deal') ?></span><span class="fa fa-star-o"></span></p>
					<h2><?php echo $block->getConfig('title');?></h2>
					<p><?php echo $block->getConfig('description');?></p>
				</div>
				<div class="border"></div>
				<div class="super-deal-countdown" data-date="<?php echo $block->getConfig('end_date');?>"></div>
			</div>
			<p class="button-view"><a href="<?php echo $category_load->getUrl();?>" class="view-all-deal btn" data-hover="<?php echo __('Shop collection') ?>"><span><?php echo __('Shop collection') ?></span></a></p>
		</div> 
		
</div>
<script type="text/javascript">
    require([
        'jquery',
        'rokanthemes/timecircles'
    ], function ($) {
		$( document ).ready(function() {
			if($('.super-deal-countdown').length>0){
				$(".super-deal-countdown").TimeCircles({
					fg_width: 0.01,
					bg_width: 1.2,
					text_size: 0.07,
					circle_bg_color: "#ffffff",
					time: {
						Days: {
							show: true,
							text: "Days",
							color: "#f9bc02"
						},
						Hours: {
							show: true,
							text: "Hours",
							color: "#f9bc02"
						},
						Minutes: {
							show: true,
							text: "Mins",
							color: "#f9bc02"
						},
						Seconds: {
							show: true,
							text: "Secs",
							color: "#f9bc02"
						}
					}
				}); 
			}
		});
    });
</script>
<?php } ?>