<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<div class="block-newsletter-form">
	<div class="block newsletter newsletter-form"> 
		<h2><?php 
				$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
				$conf = $objectManager->get('Magento\Framework\App\Config\ScopeConfigInterface')->getValue('themeoption/newsletter_form/title_content_form');  
				echo $conf;
			?>
			<?php echo $block->getConfig('title_content_form');?></h2>
		<div class="newsletter-des">
			<?php 
				$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
				$conf = $objectManager->get('Magento\Framework\App\Config\ScopeConfigInterface')->getValue('themeoption/newsletter_form/content_form');  
				echo $conf;
			?>
			<?php echo $block->getConfig('title_content_form');?>
		</div>
		
		<div class="content">
			<form class="form subscribe"
				novalidate
				action="<?php /* @escapeNotVerified */ echo $block->getFormActionUrl() ?>"
				method="post"
				data-mage-init='{"validation": {"errorClass": "mage-error"}}'
				id="newsletter-validate-detail">
				<div class="field newsletter">
					<label class="label" for="newsletter"><span><?php /* @escapeNotVerified */ echo __('Sign Up for Our Newsletter:') ?></span></label>
					<div class="control">
						<input name="email" type="email" id="newsletter"
									placeholder="<?php /* @escapeNotVerified */ echo __('Subscribe to our newsletter...') ?>"
									data-validate="{required:true, 'validate-email':true}"/>
						 <div class="actions">
							<button class="action subscribe primary" title="<?php /* @escapeNotVerified */ echo __('Subscribe') ?>" type="submit">
								<span><?php /* @escapeNotVerified */ echo __('Subscribe') ?></span>
							</button>
						</div>
					</div>
				</div>
			   
			</form>
		</div>
	</div>
</div>
