<form action="https://epic-dhawan.82-223-50-168.plesk.page/grantmacdonald_mechanics/index/index" method="POST">
    <div class="row">
        <div class="form-group col-12 col-md-6">
            <label for="">Nombre</label>
            <input type="text" class="form-control" name="name">
        </div>
        <div class="form-group col-12 col-md-6">
            <label for="">CIF</label>
            <input type="text" class="form-control" name="cif">
        </div>
        <div class="form-group col-12 col-md-6">
            <label for="">Email</label>
            <input type="text" class="form-control" name="email">
        </div>
        <div class="form-group col-12 col-md-6">
            <label for="">Teléfono</label>
            <input type="text" class="form-control" name="telefono">
        </div>
        <div class="form-group col-12">
            <label for="">Dirección</label>
            <input type="text" class="form-control" name="direccion">
        </div>
        <div class="form-group col-12">
            <label for="">Persona de contacto</label>
            <input type="text" class="form-control" name="persona_de_contacto">
        </div>
        <div class="form-group col-12">
            <label for="">Marca enganches</label>
            <input type="text" class="form-control" name="marca_enganches">
        </div>
        <div class="form-group col-12 col-md-6">
            <label for="">Precio hora</label>
            <input type="text" class="form-control" name="precio_hora">
        </div>
        <div class="form-group col-12 col-md-6">
            <label for="">Enganches montados por año</label>
            <input type="text" class="form-control" name="enganches_montados_por_ano">
        </div>
        <div class="form-group col-12">
            <button type="submit">Submit</button>
        </div>
    </div>
</form>