<?php

/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile
if($banners = $block->getBannerCollection()):
	$slider = $block->getSlider();
	$sliderId = $block->getSliderId(); 
?>
<div class="wrapper_slider hidden-xs slider_<?php echo $sliderId; ?>">
	<div class="owl">
		<?php foreach($banners as $banner){ if($banner->getSlideStatus() == '2'){ continue; }	?>
			<div class="banner_item">
				<div class="banner_item_bg">
					<?php
					$html = $block->getImageElement($banner->getSlideImage());
					if($link = $banner->getSlideLink())
						$html = '<a href="'. $link .'">' . $html . '</a>' ; 
					echo $html;
					?>
				</div>	
			</div>
		<?php } ?>
	</div>
</div>
<div class="wrapper_slider visible-xs slider_<?php echo $sliderId; ?>_mobile">
	<div class="owl">
		<?php foreach($banners as $banner){  if($banner->getSlideStatus() == '2'){ continue; }	?>
			<div class="banner_item">
				<div class="banner_item_bg">
					<?php
					$html = $block->getImageElement($banner->getSlideImageMobile());
					if($link = $banner->getSlideLink())
						$html = '<a href="'. $link .'">' . $html . '</a>' ; 
					echo $html;
					?>
				</div>	
			</div>
		<?php } ?>
	</div>
</div>
<script>
	require([
		'jquery',
		'mage/mage',
		'rokanthemes/owl'
	], function ($) {
		'use strict';
		jQuery(".slider_<?php echo $sliderId; ?>_mobile .owl").owlCarousel(
			{
				lazyLoad:true,
				<?php foreach($slider->getSliderSetting() as $key=>$value)
				{
					if(in_array($key, array('autoPlay', 'navigation', 'stopOnHover', 'pagination', 'scrollPerPage'))){
						$value == 0 ? $value = 'false': '';
						$value == 1 ? $value = 'true': '';
					}
					echo $key . ':' . $value . ',';
				} ?>}
		);
		jQuery(".slider_<?php echo $sliderId; ?> .owl").owlCarousel(
			{
				lazyLoad:true,
				<?php foreach($slider->getSliderSetting() as $key=>$value)
				{
					if(in_array($key, array('autoPlay', 'navigation', 'stopOnHover', 'pagination', 'scrollPerPage'))){
						$value == 0 ? $value = 'false': '';
						$value == 1 ? $value = 'true': '';
					}
					echo $key . ':' . $value . ',';
				} ?>}
		);
	});
</script>
<?php endif; ?>
?>

<script type="text/javascript">
	require([
		'jquery',
		'rokanthemes/choose'
	], function($) {
		$("#choose_category").chosen().change(() => {
			$.ajax({
				type: 'GET',
				url: `/scripts/get-data-for-select.php?data_type=models&id_car_brand=${$('#choose_category').val()}`,
				success: (data) => {
					data = JSON.parse(data);
					var html = '';
					for (var i = 0; i < data.length; i++) {
						html += `<option value="${data[i].id}">${data[i].label}</option>`;
					}
					$('#model_select').chosen('destroy');
					$('#model_select').html(html);
					$('#model_select').chosen();
				}
			})
		});
		$('#model_select').chosen().change(() => {
			console.log($('#model_select').val());
		});
		$('#version_select').chosen().change(() => {

		});

		function goToCategory() {
			if ($('#version_select').val() != '') {

			} else if ($('#model_select').val() != '') {

			} else if ($('#choose_category').val() != '') {

			}
		}
	});
</script>
<div style="position: relative; margin-top: 80px; min-height: 400px; width: 100%; background-image: url(D:/xampp/htdocs/enganches/assets/images/fotos/hero--background.jpg); background-size: cover; background-repeat: no-repeat; background-position: center center;">
	<div style="position: absolute; width: 100%; height: 100%; top: 0; left: 0; background: rgba(0,0,20,.5); z-index: 1;">

		<div class="block block-search">
			<div class="block block-content">
				<div class="dropdown">
					<div style="justify-content: space-between;" class="form minisearch dropdown-menu search-content <?php if ($block->enableSearchByCat()) { ?>cat-search<?php } ?>" id="search_mini_form" action="<?php /* @escapeNotVerified */ echo $helper->getResultUrl() ?>" method="get">
						<div class="field-by-cat-search">
							<select name="cat[]" id="choose_category">
								<option value="">
									<?php echo __('All Categories'); ?>
								</option>
								<?php
								foreach ($categories as $cat) {
									if (isset($_GET['cat']) && $_GET['cat'] == $cat->getId()) {
										echo '<option value="' . $cat->getId() . '" selected="selected">' . $cat->getName() . '</option>';
									} else {
										echo '<option value="' . $cat->getId() . '">' . $cat->getName() . '</option>';
									}
								}
								?>
							</select>
							<select name="cat[]" id="model_select">
							</select>
							<select name="cat[]" id="version_select">
							</select>
						</div>
						<div class="actions">
							<button onclick="goToCategory()" title="<?php echo $block->escapeHtml(__('Search')) ?>" class="action search">
								<span>
									<?php /* @escapeNotVerified */ echo __('Search'); ?>
								</span>
							</button>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>

</div>
