<?php
/**
 * Copyright © 2019 Rokanthemes. All rights reserved. 
 */

$locations = $block->getStoreLocator();
$i = 1;

$canSeeMechanics = $block->getLoggedinCustomerId();

echo var_dump($canSeeMechanics);

?>
<div id="store_list">
    <?php foreach ($locations as $location): ?>
        <div class="list" name="mapLocation" data-id="<?php echo $i ?>">
			
			<?php 
				if($location->getImageStore()){ 
					$image = json_decode($location->getImageStore());
				}else{
					$image = $block->getViewFileUrl('Rokanthemes_StoreLocator::images/shop.jpg');
				}
			?>
			<div class="card-store">
				<div class="image">
					<img src="<?php echo $image ?>"/>
				</div>
				<div class="location-information"> 
					<h2><?php echo $this->escapeHtml($location->getName()); ?></h2>
					<?php if (trim($location->getCity())) { ?>
						<div><?php echo __('City') ?>: <?php echo $this->escapeHtml($location->getCity()); ?></div>
					<?php }?>
					<?php if (trim($location->getPostcode())) { ?>
						<div><?php echo __('Zip') ?>: <?php echo $this->escapeHtml($location->getPostcode()); ?></div>
					<?php }?>
					<?php if (trim($location->getCountry())) { ?>
						<div><?php echo __('Country') ?>: <?php echo $this->escapeHtml($location->getCountry()); ?></div>
					<?php }?>
					<?php if (trim($location->getAddress())) { ?>
						<div><?php echo __('Address') ?>: <?php echo $this->escapeHtml($location->getAddress()); ?></div>
					<?php }?> 

					<div class="card-footer">
						<?php $time_today = $block->getTimeStoreLocator($location->getStoreId()) ?>
						<div class="today_time">
							<i class="far fa-clock"></i>
							<?= __('Opening Hours:')?> 
							<?php if($time_today['today'] == 0){?><?php echo __('Closed') ?><?php }else{ ?><?php if($time_today['time_today']->from->hours < 10){echo '0'.$time_today['time_today']->from->hours;} ?> : <?php if($time_today['time_today']->from->minutes < 10){echo '0'.$time_today['time_today']->from->minutes;} ?> AM - <?php if($time_today['time_today']->to->hours < 10){echo '0'.$time_today['time_today']->to->hours;} ?> : <?php if($time_today['time_today']->to->minutes < 10){echo '0'.$time_today['time_today']->to->minutes;} ?> PM <?php }?>
							<div class="locator_arrow"></div>
						</div>
						<div class="all_today_time" style="display:none;">
							<?php echo $block->getAllTimeStoreLocator($location->getStoreId()); ?>
						</div>
					</div>
					<div class="view-detail" style="margin-right: 8px;">
						<a style="margin-right: 8px;" href="<?php echo $this->getUrl('talleres/store/view/key/'.$location->getId()) ?>"><?php echo __('View Detail') ?></a>
						<a href="javascript:elegirTaller(<?php echo $location->getId(); ?>)"><?php echo __('Elegir taller') ?></a>
					</div>
				</div>
			</div>

        </div>
        <?php $i++ ?>
    <?php endforeach; ?>
</div>
<script>
	function elegirTaller(id = null) {
		if (id === null) id = 2;
		var req = new XMLHttpRequest();
		req.open('GET', `https://epic-dhawan.82-223-50-168.plesk.page/rest/V1/laclave-apitest/test?param=${id}`, true);
		req.onreadystatechange = (aEvt) => {
			if (req.readyState == 4) {
				if (req.status == 200) {
					if (req.response) {
						alert('Thanks for choosing this taller');
					} else {
						alert('User not logged in')
					}
				} else {
					dump("Error loading page\n");
				}
			}
		};
		req.send();
	}
</script>