<?php 
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$model = $objectManager->get('Magento\Variable\Model\Variable')->loadByCode('whatsapp_number');
$plain_value = $model->getPlainValue();
?>
<div class="header-container layout3">
	<div class="topbar hidden-xs hidden-sm text-center">
		<div class="container-max">
			<?php echo $this->getChildHtml("topbar_free_delivery"); ?>
		</div>
	</div>
	<div class="header">
		<div class="container-max">
			<div class="for-full-withmenu flex-layout">
				<div class="col-logo">
					<?php echo $this->getChildHtml("logo"); ?>
				</div>
				<div class="header-right">
					<span data-action="toggle-nav" class="action nav-toggle nav-toggle--sm"><span>Toggle Nav</span></span>
					<div class="language-currency">
						<div class="container-setting-language-currency">
							<?php echo $this->getChildHtml("currency"); ?>
							<?php echo $this->getChildHtml("store_language"); ?>
						</div>
					</div>
					<div class="header-top-setting hidden-xs hidden-sm">
						<div class="register-login visible-md visible-lg">
							<?php if (!$this->helper('Rokanthemes\Themeoption\Helper\Data')->isLoggedIn()) { ?>
								<a class="custom-button-login" href="<?php echo $this->getUrl('customer/account'); ?>">
									<span>
										<i class="fas fa-user-circle"></i> <?php echo __('Login'); ?>
									</span>
								</a>
							<?php
							} else {
							?>
								<a href="<?php echo $this->getUrl('customer/account/index'); ?>">
									<span>
										<i class="fas fa-user-circle"></i>
										<?php echo __('My account'); ?>
									</span>
								</a>
								<!-- <a href="<?php echo $this->getUrl('customer/account/logout'); ?>"> <?php echo __('or'); ?> <?php echo __('Logout'); ?></a> -->
							<?php } ?>
							<a href="/contact/index/">
								<span>
									<i class="fas fa-question-circle"></i> <?php echo __('Ayuda y contacto'); ?>
								</span>
							</a>
						</div>
					</div>
					<?php echo $this->getChildHtml("minicart"); ?>
				</div>
			</div>
		</div>
		<div class="header-menu">
			<div class="container-max">
				<div class="flex-layout" style="margin: 0 auto;">
					<script type="text/javascript">
						require([
							'jquery',
							'rokanthemes/verticalmenu'
						], function($) {
							$(".verticalmenu").VerticalMenu();
							$('.cms-index-index .navigation.verticalmenu .togge-menu').hide();
							$('.title-category-dropdown').click(function(event) {
								$('.navigation.verticalmenu .togge-menu').slideToggle('slow');
								$(this).toggleClass('active');
							});
							$(document).ready(function() {
								var lenghtLi = $('.cms-index-index .navigation.verticalmenu .ui-menu-item.level0').length;
								var limitItemShow = 11;
								if (lenghtLi > limitItemShow) {
									$('.navigation.verticalmenu .ui-menu-item.level0').each(function(index) {
										if (index >= (limitItemShow - 1)) {
											$(this).addClass('orther-link');
											$(this).hide();
										}
									});
									$('.navigation.verticalmenu .expand-category-link').show();
									$('.navigation.verticalmenu .expand-category-link').on("click", function() {
										$(this).toggleClass('expanding');
										$('.navigation.verticalmenu .ui-menu-item.level0.orther-link').slideToggle('slow');
									});
								}
							});
						});
					</script>
					<div class="sections nav-sections">
						<div id="close-menu" class="visible-xs visible-sm"><a href="#"><i class="icon-x"></i></a></div>
						<div class="section-items nav-sections-items" role="tablist">
							<div class="section-item-title nav-sections-item-title active" data-role="collapsible" role="tab" data-collapsible="true" aria-controls="custom.topnav" aria-selected="false" aria-expanded="true" tabindex="0">
								<a class="nav-sections-item-switch" data-toggle="switch" href="#custom.topnav"></a>
							</div>
							<div class="section-item-content nav-sections-item-content" id="custom.topnav" data-role="content" role="tabpanel" aria-hidden="false">
								<div class="navigation custommenu main-nav" role="navigation">
									<ul>
										<li class="ui-menu-item level0 classic "><a class="level-top active" href="/">Home</a></li>
										<li class="ui-menu-item level0 classic "><a class="level-top active" href="/enganches">Enganches</a></li>
										<li class="ui-menu-item level0 classic "><a class="level-top active" href="/kit-electricos">Kit eléctricos</a></li>
										<li class="ui-menu-item level0 classic "><a class="level-top active" href="/talleres">Talleres</a></li>
										<li class="ui-menu-item level0 classic "><a class="level-top active" href="/blog">Consejos</a></li>
										<li class="logo"><span data-action="toggle-nav" class="action nav-toggle"><span>Toggle Nav</span></span>
											<a class="logo active" href="https://blueskytechmage.com/gota/en3/" title="" aria-label="store logo">
												<img src="https://blueskytechmage.com/gota/pub/media/logo/stores/10/logo.png" title="" alt="" width="69" height="28">
											</a>
										</li>
									</ul>
								</div>
								<script type="text/javascript">
									require([
										'jquery',
										'rokanthemes/custommenu'
									], function($) {
										$(".custommenu").CustomMenu();
									});
								</script>
							</div>
						</div>
						<div class="mobile-action">
							<?php if (!$this->helper('Rokanthemes\Themeoption\Helper\Data')->isLoggedIn()) { ?>
								<div class="register-login visible-xs visible-sm">
									<a href="<?php echo $this->getUrl('customer/account'); ?>"><?php echo __('Login'); ?> <i class="fas fa-user-circle"></i></a>
								</div>
							<?php
							} else {
							?>
								<div class="register-login visible-xs visible-sm">
									<a href="<?php echo $this->getUrl('customer/account/index'); ?>"><?php echo __('My account'); ?> <i class="fas fa-user-circle"></i></a>
								</div>
								<div class="register-login visible-xs visible-sm">
									<a href="<?php echo $this->getUrl('customer/account/logout'); ?>"><?php echo __('Logout'); ?> <i class="fas fa-sign-out-alt"></i></a>
								</div>
							<?php } ?>
						</div>
					</div>
					<div class="holine hidden-xs hidden-sm"><p><a href="https://web.whatsapp.com/send?phone=<?php echo $plain_value; ?>&text=Hola, estoy interesado en comprar un enganche en enganches-online.es"><span class=""><i class="fab fa-whatsapp"></i> &nbsp;<?php /*echo $plain_value;*/ ?>+34 628 980 480</span></a></p></div>
				</div>
			</div>
			<?php
				// If not homepage, add search bar
				if ($this->getRequest()->getFullActionName() != "cms_index_index") {
			?>
			<div class="wrapper-fluid bg-gray-00">
				<div class="container-max">
					<div class="sFilter">
						<div class="trigger-filter--header filter--header filter--hidden-sm">
							<div class="filter-wrapper">
								<a href="javascript:void(0);">FILTRAR <div class="filter-icon"></div></a> 
							</div>
						</div>
						<?php echo $this->getChildHtml("topSearch"); ?>
					</div>
					<!--
					<?php echo $this->getChildHtml("vertical.topnav") ?>
					<?php echo $this->getChildHtml("top.navigation.sections"); ?>	
					<div class="holine hidden-xs hidden-sm"><?php echo $this->getChildHtml("holine-number"); ?></div>
					-->
				</div>
			</div>
			<?php
				}
			?>
		</div>
	</div>
</div>
<?php if ($this->helper('Rokanthemes\Themeoption\Helper\Themeconfig')->isEnableStickyHeader()) { ?>
	<script type="text/javascript">
		require(['jquery'], function($) {
			$(document).ready(function($) {
				$(window).scroll(function() {
					var num = $('.header-container').outerHeight();
					var screenWidth = $(window).width();

					if ($(this).scrollTop() > num && screenWidth >= 768) {
						$(".header").addClass("sticky");
					} else {
						$(".header").removeClass("sticky");
					}
				});
			});
		});
	</script>
<?php } ?>