<div class="page-main-actions">
    <div class="page-actions-placeholder"></div>
    <div class="page-actions" data-ui-id="page-actions-toolbar-content-header">
        <div class="page-actions-inner" data-title="Products">
            <div class="page-actions-buttons">
                <button id="add_new_product-button" title="Add Product" class="action-default primary add" data-ui-id="products-list-add-new-product-button">
                    <span>Borrar y syncronizar todo</span>
                </button>
                <button id="" title="Add Product" class="action-default primary add" data-ui-id="products-list-add-new-product-button">
                    <span>Syncronizar todo</span>
                </button>
                <button id="" title="Add Product" class="action-default primary add" data-ui-id="products-list-add-new-product-button">
                    <span>Syncronizar enganches</span>
                </button>
                <button id="" title="Add Product" class="action-default primary add" data-ui-id="products-list-add-new-product-button">
                    <span>Syncronizar kits</span>
                </button>
            </div>
        </div>
    </div>
</div>